name = "create-hono-worker-ts"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[vars]
IS_PROD = false
IS_DEV = true

[env.production]
vars = { IS_PROD = true, IS_DEV = false }

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "__YOUR_R2_BUCKET_ID__"

# [[d1_databases]]
# binding = "DB"
# database_name = "prisma-demo-db"
# database_id = "__YOUR_D1_DATABASE_ID__"

# [ai]
# binding = "AI"